# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


##### My Personal tweaks, To be cleaned up

# add brew python3 and brew to path
path=('/usr/local/opt/python/libexec/bin' $path)
path=('/usr/local/bin' $path)
export PATH

# use vim in the shell
bindkey -v

# make sure to use vim for editing things like git/cron
export EDITOR=vim

# shortcuts
alias cl=clear
alias C-l=clear
alias gs='git status'
alias gc='git commit'
alias gd='git diff'
alias ga='git add'
alias vi=nvim
alias vim=nvim
alias viz='vi ~/.zshrc'
alias jsource='source ~/.zshrc'
alias rm='rm -fv'
alias cd1='cd ..'
alias cd2='cd ../..'
alias cd3='cd ../../..'

# useful functions

function gr()
{
    root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$root" ]; then
        cd "$root"
    fi
}

# virtualenv path
export WORKON_HOME=~/.virtualenvs/

# pipenv bug (thinks it is in a virtualenv for some reason)
export PIPENV_VERBOSITY=-1

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# mysql path
export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"

function jfind()
{
	NO_ARGS=0

	if [ $# -eq "$NO_ARGS" ]
	then
		echo "please enter a term to search for"
		read case
		jfind $case;
	else
		find . -path .git -prune -o -follow -iname \*$1\*
	fi
}
